# https://hub.docker.com/r/ovrclk/akash/tags?page=1&ordering=last_updated
FROM ovrclk/akash:stable

USER root

COPY integration/setup/akash-setup.sh .

RUN chmod 777 akash-setup.sh

EXPOSE 26657

ENTRYPOINT [ "./akash-setup.sh" ]
# NOTE: to run this image, docker run -d -p 26657:26657 ./akash-setup.sh {{chain_id}} {{genesis_account}} {{seeds}} {{priv_validator_key_path}}